name: Sync to GitFlic

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config --global user.email ${{ secrets.GITFLIC_EMAIL }}
          git config --global user.name ${{ secrets.GITFLIC_USERNAME }}

      - name: Push to GitFlic
        env:
          GITFLIC_REPO: ${{ secrets.GITFLIC_REPO }}
          GITFLIC_TOKEN: ${{ secrets.GITFLIC_TOKEN }}
        run: |
          git remote add gitflic "${GITFLIC_REPO}"
          git push "https://${GITFLIC_TOKEN}@${GITFLIC_REPO#https://}"
